### ISSUE TITLE
Error 403 Forbidden

### ISSUE THREAD

**Issue by giusedm** [Blu-Tiger/streamingcommunity-unofficialapi#12]
can't open the m3u8 link and Iframe link because have page 403 forbidden

**Comment by Blu-Tiger** [comment]
it should be fixed now in version 2.0.2

**Comment by marcocianetti** [comment]
I think the error is still there, just tested with a few URLs.

Also the Readme is not updated with the latest version of `get_links` function that doesn't work with the full URL.

**Comment by Blu-Tiger** [comment]
Thank you for pointing that out, i will look at it again.

**Comment by giusedm** [comment]
any update?

**Comment by Blu-Tiger** [comment]
Still working on it, I'm trying to understand how the site generates some parts of the link

**Comment by giusedm** [comment]
i see this repo https://github.com/Lovi-0/StreamingCommunity
and the script generate working links, so you can check the code for streaming community site

**Comment by Blu-Tiger** [comment]
I've made some fixes, try the new version

**Comment by marcocianetti** [comment]
Testing now and it seems to work 👏🏻🍾

**Comment by marcocianetti** [comment]
It's down again, I think that some parameter change daily so it was working yesterday (and maybe the day you released the 2.0.2 version) but not today.

**Comment by giusedm** [comment]
i think the obly solution is libraries created in this repo https://github.com/Lovi-0/StreamingCommunity Specifically vixcloud.py and all the internal libraries connected to this script
